spring.datasource.url=jdbc:postgresql://localhost:5432/Unimarket
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


api.security.token.secret=${JWT_SECRET:unimarket_chave_local_secreta_dev_12345}

